// This file is generated by MyceliumVR.
// Do not edit by hand. Update the native BridgeRegistry instead.

function makeEntityHandle(id) {
  return {
    id,

    destroy() {
      return mycelium.destroyEntity(id);
    },

    setTransform(transform) {
      mycelium.setTransform(
        id,
        transform.px,
        transform.py,
        transform.pz,
        transform.qx ?? 0,
        transform.qy ?? 0,
        transform.qz ?? 0,
        transform.qw ?? 1,
        transform.sx ?? 1,
        transform.sy ?? 1,
        transform.sz ?? 1,
      );
      return this;
    },

    setMesh(mesh) {
      mycelium.setMesh(id, mesh);
      return this;
    },

    setMaterial(material) {
      mycelium.setMaterial(id, material);
      return this;
    },

    createPanel(url, width, height) {
      mycelium.createPanel(id, url, width, height);
      return this;
    },
  };
}

export const Mycelium = {
  native: mycelium,
  api: mycelium.api,

  fs: mycelium.fs,

  log(message) {
    mycelium.log(message);
  },

  spawnEntity() {
    return makeEntityHandle(mycelium.spawnEntity());
  },

  entityCount() {
    return mycelium.entityCount();
  },

  dirtyTransformCount() {
    return mycelium.dirtyTransformCount();
  },

  acquireTransformBuffer(capacity) {
    return mycelium.acquireTransformBuffer(capacity);
  },

  commitTransformBuffer(count) {
    return mycelium.commitTransformBuffer(count);
  },
};
