// This file is generated by MyceliumVR.
// Do not edit by hand. Update the native BridgeRegistry instead.

// Low-level AssemblyScript declarations for MyceliumVR WASM imports.
// String arguments are UTF-8 pointer/length pairs; do not pass AssemblyScript's UTF-16 string storage directly.

export type EntityId = i32;
export type BytePointer = usize;

/** Write a message to the native MyceliumVR log. */
@external("mycelium", "log")
export declare function log(messagePtr: usize, messageLen: i32): void;

/** Return the number of live native ECS entities. */
@external("mycelium", "entityCount")
export declare function entityCount(): f64;

/** Return the number of live entities with dirty transforms. */
@external("mycelium", "dirtyTransformCount")
export declare function dirtyTransformCount(): f64;

/** Create a native ECS entity and return its opaque handle. */
@external("mycelium", "spawnEntity")
export declare function spawnEntity(): i32;

/** Destroy a native ECS entity. Returns false for stale or invalid handles. */
@external("mycelium", "destroyEntity")
export declare function destroyEntity(entity: i32): bool;

/** Write a transform directly into native ECS storage. */
/** Throws: RangeError for invalid EntityId. */
@external("mycelium", "setTransform")
export declare function setTransform(entity: i32, px: f64, py: f64, pz: f64, qx: f64, qy: f64, qz: f64, qw: f64, sx: f64, sy: f64, sz: f64): bool;

/** Assign a mesh asset handle to an entity. */
/** Throws: RangeError for invalid EntityId. */
@external("mycelium", "setMesh")
export declare function setMesh(entity: i32, meshPtr: usize, meshLen: i32): bool;

/** Assign a material asset handle to an entity. */
/** Throws: RangeError for invalid EntityId. */
@external("mycelium", "setMaterial")
export declare function setMaterial(entity: i32, materialPtr: usize, materialLen: i32): bool;

/** Assign a normal map texture path to an entity. */
/** Throws: RangeError for invalid EntityId. */
@external("mycelium", "setNormalMap")
export declare function setNormalMap(entity: i32, pathPtr: usize, pathLen: i32): bool;

/** Set camera position and Euler orientation (yaw/pitch in degrees). */
@external("mycelium", "setCamera")
export declare function setCamera(px: f64, py: f64, pz: f64, yaw: f64, pitch: f64): void;

/** Set scene ambient light color and intensity. */
@external("mycelium", "setAmbientLight")
export declare function setAmbientLight(r: f64, g: f64, b: f64, intensity: f64): void;

/** Set scene directional (sun) light direction, color, and intensity. */
@external("mycelium", "setDirectionalLight")
export declare function setDirectionalLight(toX: f64, toY: f64, toZ: f64, r: f64, g: f64, b: f64, intensity: f64): void;

/** Set a point light by index (0–7): position, color, intensity, radius. */
@external("mycelium", "setPointLight")
export declare function setPointLight(index: f64, x: f64, y: f64, z: f64, r: f64, g: f64, b: f64, intensity: f64, radius: f64): void;

/** Set a spot light by index (0–7): position, direction, cone angles, color, intensity, radius. */
@external("mycelium", "setSpotLight")
export declare function setSpotLight(index: f64, x: f64, y: f64, z: f64, dirX: f64, dirY: f64, dirZ: f64, innerDeg: f64, outerDeg: f64, r: f64, g: f64, b: f64, intensity: f64, radius: f64): void;

/** Remove all active point and spot lights from the scene. */
@external("mycelium", "clearPointLights")
export declare function clearPointLights(): void;

/** Attach a WebContent panel definition to an entity. */
/** Throws: RangeError for invalid EntityId. */
@external("mycelium", "createPanel")
export declare function createPanel(entity: i32, urlPtr: usize, urlLen: i32, width: f64, height: f64): bool;

