// This file is generated by MyceliumVR.
// Do not edit by hand. Update the native BridgeRegistry instead.

export type EntityId = number;

export interface TransformArgs {
  px: number;
  py: number;
  pz: number;
  qx?: number;
  qy?: number;
  qz?: number;
  qw?: number;
  sx?: number;
  sy?: number;
  sz?: number;
}

export interface MyceliumApi {
  functions(): string[];
  hasFunction(name: string): boolean;
  describeFunction(name: string): string | undefined;
}

export interface MyceliumFileSystem {
  /** Read a UTF-8 text file from a mounted Mycelium virtual filesystem path. */
  /** Throws: Error for missing mounts, missing files, or invalid UTF-8. */
  readText(path: string): string;

  /** Return true if a mounted Mycelium virtual filesystem path exists. */
  exists(path: string): boolean;

  /** Write UTF-8 text to a mounted writable Mycelium virtual filesystem path. */
  /** Throws: TypeError for read-only mounts, missing mounts, or write failures. */
  writeText(path: string, text: string): boolean;

}

export interface MyceliumNative {
  readonly api: MyceliumApi;

  readonly fs: MyceliumFileSystem;

  /** Write a message to the native MyceliumVR log. */
  log(message: string): void;

  /** Create a native ECS entity and return its opaque handle. */
  spawnEntity(): EntityId;

  /** Destroy a native ECS entity. Returns false for stale or invalid handles. */
  destroyEntity(entity: EntityId): boolean;

  /** Return the number of live native ECS entities. */
  entityCount(): number;

  /** Return the number of live entities with dirty transforms. */
  dirtyTransformCount(): number;

  /** Write a transform directly into native ECS storage. */
  /** Throws: RangeError for invalid EntityId. */
  setTransform(entity: EntityId, px: number, py: number, pz: number, qx: number, qy: number, qz: number, qw: number, sx: number, sy: number, sz: number): boolean;

  /** Acquire a Float32Array for bulk transform writes. */
  /** Throws: RangeError for invalid capacity. */
  acquireTransformBuffer(capacity: number): Float32Array;

  /** Apply rows from the acquired transform buffer and return the accepted transform count. */
  /** Throws: RangeError for invalid count. */
  commitTransformBuffer(count: number): number;

  /** Assign a mesh asset handle to an entity. */
  /** Throws: RangeError for invalid EntityId. */
  setMesh(entity: EntityId, mesh: string): boolean;

  /** Assign a material asset handle to an entity. */
  /** Throws: RangeError for invalid EntityId. */
  setMaterial(entity: EntityId, material: string): boolean;

  /** Attach a WebContent panel definition to an entity. */
  /** Throws: RangeError for invalid EntityId. */
  createPanel(entity: EntityId, url: string, width: number, height: number): boolean;

  /**
   * Set the scene ambient light color and intensity.
   * Affects all mesh entities via the lighting shader.
   */
  setAmbientLight(r: number, g: number, b: number, intensity: number): void;

  /**
   * Set the scene directional light.
   * toX/toY/toZ is the direction *toward* the light source (normalized by the shader).
   * r/g/b is the light color; intensity scales it.
   */
  setDirectionalLight(toX: number, toY: number, toZ: number, r: number, g: number, b: number, intensity: number): void;

  /**
   * Return the current scene light state, or null if no renderer is available.
   */
  getSceneLight(): {
    ambientR: number; ambientG: number; ambientB: number; ambientIntensity: number;
    lightToX: number; lightToY: number; lightToZ: number; lightIntensity: number;
    lightR: number; lightG: number; lightB: number;
  } | null;

}

export interface EntityHandle {
  readonly id: EntityId;
  destroy(): boolean;
  setTransform(transform: TransformArgs): this;
  setMesh(mesh: string): this;
  setMaterial(material: string): this;
  createPanel(url: string, width: number, height: number): this;
}

export interface MyceliumSDK {
  readonly native: MyceliumNative;
  readonly api: MyceliumApi;

  readonly fs: MyceliumFileSystem;

  log(message: string): void;
  spawnEntity(): EntityHandle;
  entityCount(): number;
  dirtyTransformCount(): number;
  acquireTransformBuffer(capacity: number): Float32Array;
  commitTransformBuffer(count: number): number;
}

export declare const Mycelium: MyceliumSDK;

declare global {
  const mycelium: MyceliumNative;

  function start(): void;
  function update(deltaTime: number): void;
}
