// This file is generated by MyceliumVR.
// Do not edit by hand. Update the native BridgeRegistry instead.

export type EntityId = number;

export interface TransformArgs {
  px: number;
  py: number;
  pz: number;
  qx?: number;
  qy?: number;
  qz?: number;
  qw?: number;
  sx?: number;
  sy?: number;
  sz?: number;
}

export interface MyceliumApi {
  functions(): string[];
  hasFunction(name: string): boolean;
  describeFunction(name: string): string | undefined;
}

export interface MyceliumFileSystem {
}

export interface MyceliumNative {
  readonly api: MyceliumApi;

  readonly fs: MyceliumFileSystem;

  /** Write a message to the native MyceliumVR log. */
  log(message: string): void;

  /** Return the number of live native ECS entities. */
  entityCount(): number;

  /** Return the number of live entities with dirty transforms. */
  dirtyTransformCount(): number;

  /** Create a native ECS entity and return its opaque handle. */
  spawnEntity(): EntityId;

  /** Destroy a native ECS entity. Returns false for stale or invalid handles. */
  destroyEntity(entity: EntityId): boolean;

  /** Return the EntityId at a given dense-array index, or null if out of range. */
  entityIdAt(index: number): EntityId;

  /** Write a transform directly into native ECS storage. */
  /** Throws: RangeError for invalid EntityId. */
  setTransform(entity: EntityId, px: number, py: number, pz: number, qx: number, qy: number, qz: number, qw: number, sx: number, sy: number, sz: number): boolean;

  /** Return the current transform of an entity as an object {px,py,pz,qx,qy,qz,qw,sx,sy,sz}, or null. */
  /** Throws: RangeError for invalid EntityId. */
  getTransform(entity: EntityId): number;

  /** Acquire a Float32Array for bulk transform writes. */
  /** Throws: RangeError for invalid capacity. */
  acquireTransformBuffer(capacity: number): Float32Array;

  /** Apply rows from the acquired transform buffer and return the accepted transform count. */
  /** Throws: RangeError for invalid count. */
  commitTransformBuffer(count: number): number;

  /** Assign a mesh asset handle to an entity. */
  /** Throws: RangeError for invalid EntityId. */
  setMesh(entity: EntityId, mesh: string): boolean;

  /** Assign a material asset handle to an entity. */
  /** Throws: RangeError for invalid EntityId. */
  setMaterial(entity: EntityId, material: string): boolean;

  /** Assign a normal map texture path to an entity. */
  /** Throws: RangeError for invalid EntityId. */
  setNormalMap(entity: EntityId, path: string): boolean;

  /** Load a glTF asset and spawn one entity per (node × primitive), applying each node's world transform. Returns an Array of EntityId numbers. */
  /** Throws: Error if the scene fails to load or no VFS is available. */
  spawnScene(path: string): number;

  /** Set camera position and Euler orientation (yaw/pitch in degrees). */
  setCamera(px: number, py: number, pz: number, yaw: number, pitch: number): void;

  /** Return current camera state as {px,py,pz,yaw,pitch}, or null if no camera. */
  getCamera(): number;

  /** Set scene ambient light color and intensity. */
  setAmbientLight(r: number, g: number, b: number, intensity: number): void;

  /** Set scene directional (sun) light direction, color, and intensity. */
  setDirectionalLight(toX: number, toY: number, toZ: number, r: number, g: number, b: number, intensity: number): void;

  /** Set a point light by index (0–7): position, color, intensity, radius. */
  setPointLight(index: number, x: number, y: number, z: number, r: number, g: number, b: number, intensity: number, radius: number): void;

  /** Set a spot light by index (0–7): position, direction, cone angles, color, intensity, radius. */
  setSpotLight(index: number, x: number, y: number, z: number, dirX: number, dirY: number, dirZ: number, innerDeg: number, outerDeg: number, r: number, g: number, b: number, intensity: number, radius: number): void;

  /** Remove all active point and spot lights from the scene. */
  clearPointLights(): void;

  /** Return current scene light state as an object, or null if not set. */
  getSceneLight(): number;

  /** Return an object with all live component data for an entity: transform, meshRenderer, panel, cullOverride, tags. Returns null for invalid entities. */
  getEntityComponents(entity: EntityId): number;

  /** Return an array of all live entities with name, kind, parent, alpha mode, and static flag. */
  getEntityHierarchy(): number;

  /** Set the selected entity by ID, clearing any previous selection. Fires __myceliumSelectionChanged in the overlay. */
  setSelectedEntity(entity: EntityId): void;

  /** Attach a WebContent panel definition to an entity. */
  /** Throws: RangeError for invalid EntityId. */
  createPanel(entity: EntityId, url: string, width: number, height: number): boolean;

}

export interface EntityHandle {
  readonly id: EntityId;
  destroy(): boolean;
  setTransform(transform: TransformArgs): this;
  setMesh(mesh: string): this;
  setMaterial(material: string): this;
  createPanel(url: string, width: number, height: number): this;
}

export interface MyceliumSDK {
  readonly native: MyceliumNative;
  readonly api: MyceliumApi;

  readonly fs: MyceliumFileSystem;

  log(message: string): void;
  spawnEntity(): EntityHandle;
  entityCount(): number;
  dirtyTransformCount(): number;
  acquireTransformBuffer(capacity: number): Float32Array;
  commitTransformBuffer(count: number): number;
}

export declare const Mycelium: MyceliumSDK;

declare global {
  const mycelium: MyceliumNative;

  function start(): void;
  function update(deltaTime: number): void;
}
