/*
 * MyceliumVR - a social VR platform built on the Ladybird browser engine
 * SPDX-License-Identifier: BSD-2-Clause
 */

#include "SDKGenerator.h"

#include "BridgeRegistry.h"

#include <AK/Format.h>
#include <AK/String.h>
#include <AK/StringBuilder.h>
#include <LibCore/File.h>

namespace MyceliumVR {

static ErrorOr<void> write_text_file(StringView path, StringView text)
{
    auto file = TRY(Core::File::open(path, Core::File::OpenMode::Write | Core::File::OpenMode::Truncate));
    TRY(file->write_until_depleted(text.bytes()));
    return {};
}

static String sdk_path(StringView output_directory, StringView filename)
{
    return MUST(String::formatted("{}/{}", output_directory.trim("/"sv, TrimMode::Right), filename));
}

static String ts_type(BridgeValueType type)
{
    switch (type) {
    case BridgeValueType::Void:
        return "void"_string;
    case BridgeValueType::Boolean:
        return "boolean"_string;
    case BridgeValueType::Number:
        return "number"_string;
    case BridgeValueType::String:
        return "string"_string;
    case BridgeValueType::EntityId:
        return "EntityId"_string;
    case BridgeValueType::Float32Array:
        return "Float32Array"_string;
    }
    VERIFY_NOT_REACHED();
}

static void append_generated_header(StringBuilder& builder)
{
    builder.append("// This file is generated by MyceliumVR.\n"sv);
    builder.append("// Do not edit by hand. Update the native BridgeRegistry instead.\n\n"sv);
}

static ErrorOr<String> generate_typescript_declarations()
{
    StringBuilder builder;
    append_generated_header(builder);
    builder.append("export type EntityId = number;\n\n"sv);
    builder.append("export interface TransformArgs {\n"sv);
    builder.append("  px: number;\n  py: number;\n  pz: number;\n"sv);
    builder.append("  qx?: number;\n  qy?: number;\n  qz?: number;\n  qw?: number;\n"sv);
    builder.append("  sx?: number;\n  sy?: number;\n  sz?: number;\n"sv);
    builder.append("}\n\n"sv);
    builder.append("export interface MyceliumApi {\n"sv);
    builder.append("  functions(): string[];\n"sv);
    builder.append("  hasFunction(name: string): boolean;\n"sv);
    builder.append("  describeFunction(name: string): string | undefined;\n"sv);
    builder.append("}\n\n"sv);
    builder.append("export interface MyceliumFileSystem {\n"sv);
    for (auto const& function : BridgeRegistry::the().functions()) {
        if (!function.js_exposed || function.js_namespace != "fs"sv)
            continue;
        builder.appendff("  /** {} */\n", function.description);
        if (!function.throws.is_empty())
            builder.appendff("  /** Throws: {} */\n", function.throws);
        builder.appendff("  {}(", function.name);
        for (size_t i = 0; i < function.arguments.size(); ++i) {
            auto const& argument = function.arguments[i];
            if (i > 0)
                builder.append(", "sv);
            builder.appendff("{}: {}", argument.name, ts_type(argument.type));
        }
        builder.appendff("): {};\n\n", ts_type(function.return_type));
    }
    builder.append("}\n\n"sv);
    builder.append("export interface MyceliumNative {\n"sv);
    builder.append("  readonly api: MyceliumApi;\n\n"sv);
    builder.append("  readonly fs: MyceliumFileSystem;\n\n"sv);

    for (auto const& function : BridgeRegistry::the().functions()) {
        if (!function.js_exposed || !function.js_namespace.is_empty())
            continue;
        builder.appendff("  /** {} */\n", function.description);
        if (!function.throws.is_empty())
            builder.appendff("  /** Throws: {} */\n", function.throws);
        builder.appendff("  {}(", function.name);
        for (size_t i = 0; i < function.arguments.size(); ++i) {
            auto const& argument = function.arguments[i];
            if (i > 0)
                builder.append(", "sv);
            builder.appendff("{}: {}", argument.name, ts_type(argument.type));
        }
        builder.appendff("): {};\n\n", ts_type(function.return_type));
    }

    builder.append("}\n\n"sv);
    builder.append("export interface EntityHandle {\n"sv);
    builder.append("  readonly id: EntityId;\n"sv);
    builder.append("  destroy(): boolean;\n"sv);
    builder.append("  setTransform(transform: TransformArgs): this;\n"sv);
    builder.append("  setMesh(mesh: string): this;\n"sv);
    builder.append("  setMaterial(material: string): this;\n"sv);
    builder.append("  createPanel(url: string, width: number, height: number): this;\n"sv);
    builder.append("}\n\n"sv);
    builder.append("export interface MyceliumSDK {\n"sv);
    builder.append("  readonly native: MyceliumNative;\n"sv);
    builder.append("  readonly api: MyceliumApi;\n\n"sv);
    builder.append("  readonly fs: MyceliumFileSystem;\n\n"sv);
    builder.append("  log(message: string): void;\n"sv);
    builder.append("  spawnEntity(): EntityHandle;\n"sv);
    builder.append("  entityCount(): number;\n"sv);
    builder.append("  dirtyTransformCount(): number;\n"sv);
    builder.append("  acquireTransformBuffer(capacity: number): Float32Array;\n"sv);
    builder.append("  commitTransformBuffer(count: number): number;\n"sv);
    builder.append("}\n\n"sv);
    builder.append("export declare const Mycelium: MyceliumSDK;\n\n"sv);
    builder.append("declare global {\n"sv);
    builder.append("  const mycelium: MyceliumNative;\n\n"sv);
    builder.append("  function start(): void;\n"sv);
    builder.append("  function update(deltaTime: number): void;\n"sv);
    builder.append("}\n"sv);
    return builder.to_string();
}

static ErrorOr<String> generate_javascript_wrapper()
{
    StringBuilder builder;
    append_generated_header(builder);
    builder.append("function makeEntityHandle(id) {\n"sv);
    builder.append("  return {\n"sv);
    builder.append("    id,\n\n"sv);
    builder.append("    destroy() {\n      return mycelium.destroyEntity(id);\n    },\n\n"sv);
    builder.append("    setTransform(transform) {\n"sv);
    builder.append("      mycelium.setTransform(\n"sv);
    builder.append("        id,\n        transform.px,\n        transform.py,\n        transform.pz,\n"sv);
    builder.append("        transform.qx ?? 0,\n        transform.qy ?? 0,\n        transform.qz ?? 0,\n        transform.qw ?? 1,\n"sv);
    builder.append("        transform.sx ?? 1,\n        transform.sy ?? 1,\n        transform.sz ?? 1,\n"sv);
    builder.append("      );\n      return this;\n    },\n\n"sv);
    builder.append("    setMesh(mesh) {\n      mycelium.setMesh(id, mesh);\n      return this;\n    },\n\n"sv);
    builder.append("    setMaterial(material) {\n      mycelium.setMaterial(id, material);\n      return this;\n    },\n\n"sv);
    builder.append("    createPanel(url, width, height) {\n      mycelium.createPanel(id, url, width, height);\n      return this;\n    },\n"sv);
    builder.append("  };\n}\n\n"sv);
    builder.append("export const Mycelium = {\n"sv);
    builder.append("  native: mycelium,\n"sv);
    builder.append("  api: mycelium.api,\n\n"sv);
    builder.append("  fs: mycelium.fs,\n\n"sv);
    builder.append("  log(message) {\n    mycelium.log(message);\n  },\n\n"sv);
    builder.append("  spawnEntity() {\n    return makeEntityHandle(mycelium.spawnEntity());\n  },\n\n"sv);
    builder.append("  entityCount() {\n    return mycelium.entityCount();\n  },\n\n"sv);
    builder.append("  dirtyTransformCount() {\n    return mycelium.dirtyTransformCount();\n  },\n"sv);
    builder.append("\n  acquireTransformBuffer(capacity) {\n    return mycelium.acquireTransformBuffer(capacity);\n  },\n"sv);
    builder.append("\n  commitTransformBuffer(count) {\n    return mycelium.commitTransformBuffer(count);\n  },\n"sv);
    builder.append("};\n"sv);
    return builder.to_string();
}

static String wasm_type(BridgeArgument const& argument)
{
    switch (argument.type) {
    case BridgeValueType::EntityId:
        return "i32"_string;
    case BridgeValueType::Boolean:
        return "i32"_string;
    case BridgeValueType::Number:
        return "f32"_string;
    case BridgeValueType::String:
        return "ptr, len"_string;
    case BridgeValueType::Void:
        return "void"_string;
    case BridgeValueType::Float32Array:
        return "ptr"_string;
    }
    VERIFY_NOT_REACHED();
}

static String wasm_return_type(BridgeValueType type)
{
    switch (type) {
    case BridgeValueType::Void:
        return "void"_string;
    case BridgeValueType::EntityId:
    case BridgeValueType::Boolean:
        return "i32"_string;
    case BridgeValueType::Number:
        return "f64"_string;
    case BridgeValueType::String:
        return "ptr, len"_string;
    case BridgeValueType::Float32Array:
        return "ptr"_string;
    }
    VERIFY_NOT_REACHED();
}

static ErrorOr<String> generate_wasm_imports()
{
    StringBuilder builder;
    builder.append("# MyceliumVR WASM Imports\n\n"sv);
    builder.append("This file is generated by MyceliumVR from the native BridgeRegistry.\n\n"sv);
    builder.append("| Module | Import | Parameters | Result | Notes |\n"sv);
    builder.append("| --- | --- | --- | --- | --- |\n"sv);
    for (auto const& function : BridgeRegistry::the().functions()) {
        if (!function.wasm_exposed)
            continue;
        builder.appendff("| mycelium | {} | ", function.name);
        if (function.arguments.is_empty()) {
            builder.append("none"sv);
        } else {
            for (size_t i = 0; i < function.arguments.size(); ++i) {
                if (i > 0)
                    builder.append(", "sv);
                builder.append(wasm_type(function.arguments[i]));
            }
        }
        builder.appendff(" | {} | {}", wasm_return_type(function.return_type), function.description);
        if (function.hot_path)
            builder.append(" Hot path."sv);
        builder.append(" |\n"sv);
    }
    return builder.to_string();
}

static ErrorOr<String> generate_api_json()
{
    StringBuilder builder;
    builder.append("{\n"sv);
    builder.append("  \"apiName\": \"mycelium\",\n"sv);
    builder.append("  \"sdkName\": \"Mycelium\",\n"sv);
    builder.append("  \"functions\": [\n"sv);
    auto const& functions = BridgeRegistry::the().functions();
    for (size_t i = 0; i < functions.size(); ++i) {
        auto const& function = functions[i];
        builder.append("    {\n"sv);
        builder.appendff("      \"module\": \"{}\",\n", function.module);
        builder.appendff("      \"jsNamespace\": \"{}\",\n", function.js_namespace);
        builder.appendff("      \"name\": \"{}\",\n", function.name);
        builder.appendff("      \"description\": \"{}\",\n", function.description);
        builder.appendff("      \"returnType\": \"{}\",\n", bridge_value_type_name(function.return_type));
        builder.appendff("      \"hotPath\": {},\n", function.hot_path ? "true"sv : "false"sv);
        builder.append("      \"args\": ["sv);
        for (size_t argument_index = 0; argument_index < function.arguments.size(); ++argument_index) {
            auto const& argument = function.arguments[argument_index];
            if (argument_index > 0)
                builder.append(", "sv);
            builder.appendff("{{ \"name\": \"{}\", \"type\": \"{}\" }}", argument.name, bridge_value_type_name(argument.type));
        }
        builder.append("]\n"sv);
        builder.append("    }"sv);
        if (i + 1 < functions.size())
            builder.append(","sv);
        builder.append("\n"sv);
    }
    builder.append("  ]\n"sv);
    builder.append("}\n"sv);
    return builder.to_string();
}

ErrorOr<void> generate_sdk(StringView target, StringView output_directory)
{
    auto normalized_target = target.is_empty() ? "all"sv : target;

    auto write_typescript = normalized_target == "all"sv || normalized_target == "typescript"sv || normalized_target == "ts"sv;
    auto write_javascript = normalized_target == "all"sv || normalized_target == "javascript"sv || normalized_target == "js"sv;
    auto write_wasm = normalized_target == "all"sv || normalized_target == "wasm"sv;
    auto write_json = normalized_target == "all"sv || normalized_target == "json"sv || normalized_target == "api-json"sv;

    if (!write_typescript && !write_javascript && !write_wasm && !write_json)
        return Error::from_string_literal("Unknown SDK target. Use all, typescript, javascript, wasm, or json.");

    if (write_typescript)
        TRY(write_text_file(sdk_path(output_directory, "mycelium.d.ts"sv), TRY(generate_typescript_declarations())));
    if (write_javascript)
        TRY(write_text_file(sdk_path(output_directory, "mycelium.js"sv), TRY(generate_javascript_wrapper())));
    if (write_wasm)
        TRY(write_text_file(sdk_path(output_directory, "wasm-imports.md"sv), TRY(generate_wasm_imports())));
    if (write_json)
        TRY(write_text_file(sdk_path(output_directory, "mycelium-api.json"sv), TRY(generate_api_json())));

    return {};
}

}
